# Use root/example as user/password credentials
version: '3.1'

# docker network create mynet

services:
  # docker run -d --name mongodb --network mynet --restart=always \
  # -e MONGO_INITDB_ROOT_USERNAME=root \
  # -e MONGO_INITDB_ROOT_PASSWORD=example
  # mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

# docker run -d --name mongo-express --network mynet --restart=always \
# -p 8081:8081 \
# -e ME_CONFIG_MONGODB_ADMINUSERNAME=root \
# -e ME_CONFIG_MONGODB_ADMINPASSWORD=example \
# -e ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/" \
# mongo-express

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

# firefox http://localhost:8081
