---
- name: 설정
  hosts: all
  tasks:
    - name: selinux 기능 permissive
      selinux:
        policy: targeted
        state: permissive
        
    - name: 방화벽 내리기
      service: 
        name: firewalld
        state: stopped
        enabled: no

    - name: 패키지 설치
      yum:
        name:
          - gnome-tweaks
          - git
        state: present

    - name: 환경 설정 배포
      template:
        src: templates/bashrc.j2
        dest: '/root/.bashrc'
        owner: root
        group: root
        mode: '0644'
      
    - name: 바탕화면 아이콘 생성
      copy:
       src: "{{ item }}"
       dest: '/root/바탕화면/'
      with_items:
        - /usr/share/applications/org.gnome.Terminal.desktop

    - name: /etc/hosts 파일 작업
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

